## Dhcpd.configuration
sudo nano /etc/dhcp/dhcpd.conf
# dhcp setting
default-lease-time 600;
max-lease-time 7200;
#dhcp server authoritative
authoritative;
subnet 192.168.129.0 netmask 255.255.255.0 {
  range 192.168.129.10 192.168.129.100;
  option routers 192.168.129.2;
  option domain-name-server 192.168.129.2;
  option domain-name "home.lab";
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.129.255;
}
